### ISSUE TITLE
PyTorch 1.2 Can't transfer anything to GPU

### ISSUE THREAD

**Issue by Erik-Sovereign** [microsoft/WSL#5477]
Environment
```
Windows build number: Version 2004 (Build 20150.1000)
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
Linux Kernel: 4.19.121-microsoft-standard
Python: 3.5.4
PyTorch: 1.2
Geforce Driver: 455.41
```

# Steps to reproduce
```
import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = torch.zeros(1, 1, 10)
tensor.to(device)
```
torch.cuda.is_available() returns true.

#  Expected behavior
PyTorch should transfer the tensor to the GPU.

# Actual behavior
It crashes with 
`CUDA error: unknown error`

**Comment by sailyung** [comment]
I find its ok;
i use ubuntu 20.04
 pip install torch==1.5.1 torchvision==0.6.1
i am not install cuda just torch 1.5.1 and torchvision

```
(test) lab@pc_yqh:~$ python
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
.zeros(1, 1, 10)
```

**Comment by Erik-Sovereign** [comment]
When I update my torch and pytorch version with
`pip3.5 install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
the code runs without an error but doesn't work either.

```
import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = torch.rand(1, 1, 10)
tensor.to(device)

tensor_two = tensor + tensor
```
runs and torch.cuda.is_available() still returns true. But if I inspect `tensor_two` at the end the device attribute of it is `device(type="cpu")`. 

And I want to work with PyTorch Version 1.2, not 1.5.1.

**Comment by sailyung** [comment]
> When I update my torch and pytorch version with
> `pip3.5 install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
> the code runs without an error but doesn't work either.
> 
> ```
> import torch
> 
> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> tensor = torch.rand(1, 1, 10)
> tensor.to(device)
> 
> tensor_two = tensor + tensor
> ```
> 
> runs and torch.cuda.is_available() still returns true. But if I inspect `tensor_two` at the end the device attribute of it is `device(type="cpu")`.
> 
> And I want to work with PyTorch Version 1.2, not 1.5.1.

```
>>> import torch
>>> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
>>> device
device(type='cuda', index=0)
>>> tensor = torch.rand(1, 1, 10)
>>> tensor
tensor([[[0.0096, 0.1139, 0.7168, 0.8277, 0.4454, 0.5753, 0.7148, 0.4055,
          0.8267, 0.7882]]])
>>> tensor.to(device)
tensor([[[0.0096, 0.1139, 0.7168, 0.8277, 0.4454, 0.5753, 0.7148, 0.4055,
          0.8267, 0.7882]]], device='cuda:0')
>>> tensor
tensor([[[0.0096, 0.1139, 0.7168, 0.8277, 0.4454, 0.5753, 0.7148, 0.4055,
          0.8267, 0.7882]]])
>>> tensor = tensor.to(device)
>>> tensor
tensor([[[0.0096, 0.1139, 0.7168, 0.8277, 0.4454, 0.5753, 0.7148, 0.4055,
          0.8267, 0.7882]]], device='cuda:0')
>>> tensor_two = tensor + tensor
>>> tensor_two
tensor([[[0.0192, 0.2279, 1.4336, 1.6553, 0.8908, 1.1505, 1.4295, 0.8111,
          1.6534, 1.5763]]], device='cuda:0')
```

**Comment by devsnets** [comment]
any news on this issue?

**Comment by Erik-Sovereign** [comment]
This is now working with
```
PyTorch: 1.5.1 (CUDA 10.1)
Python: 3.5.9
```
instead of my previous setup
```
PyTorch: 1.2 (CUDA 10)
Python: 3.5.4
```

I would still consider it as a problem though since I would like to work with PyTorch 1.2 since it is the version that we use in our workplace.

Maybe this helps you @keesschollaart81
