### ISSUE TITLE
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by geg00** [microsoft/WSL#5598]
I just follow the installation step by step here 
https://docs.nvidia.com/cuda/wsl-user-guide/index.html

I'm not trying to use docker I'm trying to use pytorch directly from python
This is the code
``
(base) gegg00@DESKTOP-KS0OLS9:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.randn(5)
tensor([-2.6408, -1.0831, -1.6984,  0.4742, -0.5909])
>>> torch.randn(5).to(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
``

# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.20170.0 Microsoft Windows NT 10.0.20170.0

Ubuntu
Release:        18.04

WSL 2:
Linux version 4.19.121-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Fri Jun 19 21:06:10 UTC 2020

# Steps to reproduce

I follow the steps 
https://docs.nvidia.com/cuda/wsl-user-guide/index.html
Installed Anaconda Anaconda3-2020.02-Linux-x86_64.sh
Installed pytorch 
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
try the code
``
(base) gegg00@DESKTOP-KS0OLS9:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.randn(5)
tensor([-2.6408, -1.0831, -1.6984,  0.4742, -0.5909])
>>> torch.randn(5).to(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
``
Getting this error:
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

#  Expected behavior

# Actual behavior

**Comment by onomatopellan** [comment]
You should try the the new nvidia driver 460.15 and last kernel 4.19.128-microsoft-standard. Both have fixes for CUDA in WSL2.
https://developer.nvidia.com/cuda/wsl/download

**Comment by npitsillos** [comment]
I have the same problem and have the same kernel version but nvidia driver 460.20 torch.cuda.is_available() returns true but cannot perform any operation on cuda

**Comment by carson-sestili** [comment]
I am having the same problem, with NVIDIA driver 460.20, and WSL 2 kernel version 4.19.128.

**Comment by sdertien** [comment]
Same problem.  NVIDIA 460.20 and WSL 2 4.19.128.  It fails even with the NVIDIA Sample for BlackSholes.  I even have two GPU's that show up in the Device Query and same issue.  And the same thing with our use of Torch CUDA.

**Comment by yhtgrace** [comment]
Same problem as well. `DeviceQuery` runs but not `BlackScholes` or `bandwidthTest`, which both error with `code=46(cudaErrorDevicesUnavailable)`. In pytorch, `torch.cuda.is_available()` returns `True` but sending anything to CUDA returns `RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable`

I started running into this today with NVIDIA 460.15, WSL 2 4.19.128, Windows 20226.1000. I then updated the driver to NVIDIA 460.20, uninstalled/reinstalled `cuda-toolkit-11.1`, restarted windows/wsl, but am still facing the same issues. `wsl --status` reports that `Windows Subsystem for Linux was last updated on 9/7/2020`, while Windows 10 Insider Preview 20226.1000 was updated 10/3/2020. Could the windows update have broke this?

**Comment by yhtgrace** [comment]
Thanks @rohitsingh02! Rolling back to 20221.1000 (while staying at WSL 2 4.19.128, NVIDIA 460.15) resolved the issue for me

**Comment by borgarpa** [comment]
> @yhtgrace Here is a quick fix:
> 
> Go to `Settings` -> `Recovery` -> Click on `Get Started` under **Go back to previous version of Windows 10**
> 
> This will take 5-10 minutes to roll back to previous version.

It may work. But there was an unfixed issue in version 20221 that caused the following error when running the Linux distro: “The remote procedure call failed”

I guess we just have to wait until Windows gets fixed again.

**Comment by PeerXu** [comment]
I got the same problem, but my Windows upgrade from very old version(19042.546).
So when I try to update Windows, it will download Windows 10 Insider Preview 20231.1000, but seem this version not work.
There is any way to upgrade to 20231.1000?

**Comment by PeerXu** [comment]
I try to downgrade to 20221 but got another [bug](https://github.com/microsoft/WSL/issues/5907).

**Comment by ForbiddenEra** [comment]
On WSL 2 / 20231.10005 / Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

`
(fastai) forbiddenera@forbiddenera:/usr/local/cuda/samples/bin/x86_64/linux/release$ ./deviceQueryDrv
./deviceQueryDrv Starting...

CUDA Device Query (Driver API) statically linked version
Detected 1 CUDA Capable device(s)

Device 0: "GeForce RTX 2070 SUPER"
  CUDA Driver Version:                           11.2
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 8192 MBytes (8589934592 bytes)
  (40) Multiprocessors, ( 64) CUDA Cores/MP:     2560 CUDA Cores
  GPU Max Clock rate:                            1905 MHz (1.90 GHz)
  Memory Clock rate:                             7001 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 4194304 bytes
  Max Texture Dimension Sizes                    1D=(131072) 2D=(131072, 65536) 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size (x,y,z):    (2147483647, 65535, 65535)
  Texture alignment:                             512 bytes
  Maximum memory pitch:                          2147483647 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Concurrent kernel execution:                   Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
Result = PASS
(fastai) forbiddenera@forbiddenera:/usr/local/cuda/samples/bin/x86_64/linux/release$ ./convolutionFFT2D
[./convolutionFFT2D] - Starting...
GPU Device 0: "Turing" with compute capability 7.5

Testing built-in R2C / C2R FFT-based convolution
...allocating memory
CUDA error at main.cpp:118 code=46(cudaErrorDevicesUnavailable) "cudaMalloc((void **)&d_Data, dataH * dataW * sizeof(float))"
`

Any other workaround than 20221? I only just hopped on WI for WSL2 / CUDA support in the last day so I think I went straight to 20231 from 1903 so not sure I can even easily downgrade.

**Comment by carson-sestili** [comment]
If it helps, what I chose to do as a workaround is simply run my CUDA code on the Windows command line as opposed to WSL. Of course, this requires that you reproduce whatever setup you had in WSL, e.g. installing packages. It's not really a solution, because you're just using a different OS, but hopefully it helps you do your work :)

**Comment by onomatopellan** [comment]
This should be fixed on build 20236. Do you still have this issue?

**Comment by ForbiddenEra** [comment]
> 
> 
> If it helps, what I chose to do as a workaround is simply run my CUDA code on the Windows command line as opposed to WSL. Of course, this requires that you reproduce whatever setup you had in WSL, e.g. installing packages. It's not really a solution, because you're just using a different OS, but hopefully it helps you do your work :)

Unfortunately I was trying to use the fastai lib which specifically really doesn't support Windows. 

Build 20236 seems to work:
```
(fastai) forbiddenera@FORBIDDENERA:~$ sudo docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
        -fullscreen       (run n-body simulation in fullscreen mode)
        -fp64             (use double precision floating point values for simulation)
        -hostmem          (stores simulation data in host memory)
        -benchmark        (run benchmark to measure performance)
        -numbodies=<N>    (number of bodies (>= 1) to run in simulation)
        -device=<d>       (where d=0,1,2.... for the CUDA device to use)
        -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
        -compare          (compares simulation results running once on the default GPU and once on the CPU)
        -cpu              (run n-body simulation on the CPU)
        -tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
MapSMtoCores for SM 7.5 is undefined.  Default to use 64 Cores/SM
GPU Device 0: "GeForce RTX 2070 SUPER" with compute capability 7.5

> Compute 7.5 CUDA device: [GeForce RTX 2070 SUPER]
40960 bodies, total time for 10 iterations: 57.387 ms
= 292.352 billion interactions per second
= 5847.040 single-precision GFLOP/s at 20 flops per interaction
```

Thanks guys! Now to just get fastai working..heh

**Comment by carson-sestili** [comment]
FYI, this worked for me on build 20236! Both the minimal example (`torch.randn(1).to(0)`) and training a full torch model. Thanks for your help, everyone :)
