### ISSUE TITLE
 /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

### ISSUE THREAD

**Issue by PureHing** [microsoft/WSL#5663]
# Environment
+ WIN10 Insider Preview 20175.rs_prerelease.200717-1349
+ WSL2 ->ubuntu18.04
+ darknet-CUDA
# Question
I can successfully use tensorflow-gpu under ubuntu18.04-wsl2 with install *455.41_gameready_win10-dch_64bit_international.exe*, but when I start to compile darknet it prompts error :
       ```sh
             /usr/bin/ld: cannot find -lcuda
            collect2: error: ld returned 1 exit status
       ```
So i execute ``sudo ldconfig -v``:
```sh
/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

 libcuda.so.1 -> libcuda.so.1.1
```
Then execute `` sudo ln -sf /usr/lib/wsl/lib/libcuda.so.1.1 /usr/lib/wsl/lib/libcuda.so.1``,
it prompts ``ln: failed to create symbolic link '/usr/lib/wsl/lib/libcuda.so.1': Read-only file system``

**How can I successfully compile darknet？Thanks**

**Comment by alexcdot** [comment]
I was able to build darknet by making a symlink to the directory where the rest of my cuda library files were `/usr/local/cuda/lib64`  by doing:

` sudo ln -s /usr/lib/wsl/lib/libcuda.so.1 /usr/local/cuda/lib64/libcuda.so`

With the help of: https://github.com/pjreddie/darknet/issues/1480

**Comment by sanwz** [comment]
> I was able to build darknet by making a symlink to the directory where the rest of my cuda library files were `/usr/local/cuda/lib64` by doing:
> 
> ` sudo ln -s /usr/lib/wsl/lib/libcuda.so.1 /usr/local/cuda/lib64/libcuda.so`
> 
> With the help of: [pjreddie/darknet#1480](https://github.com/pjreddie/darknet/issues/1480)

I don't find the folder /usr/lib/wsl,  How do you get it ? Or how do you install the cuda?

**Comment by alexcdot** [comment]
This is specifically for Nvidia CUDA in WSL 2 with the Windows Insider Preview on the Dev Channel. I followed this guide after I had Windows Insider Preview on Dev Channel set up: https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl

**Comment by sanwz** [comment]
> This is specifically for Nvidia CUDA in WSL 2 with the Windows Insider Preview on the Dev Channel. I followed this guide after I had Windows Insider Preview on Dev Channel set up: https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl

Well, I installed again followed your providing link, I don't find the libcuda.so , I just find one libcuda.so.1 in the path: /mnt/Windows/System32/lxss/lib.

**Comment by John-Joubert** [comment]
Please review response post by @Phyx-Meow re: #https://github.com/yuk7/ArchWSL/issues/248.  
As he points out, it really has nothing to do with your Linux install.  It's a simple fix in Windows. 
The solution he posts is for Arch, but the fix is exactly same for Ubuntu, etc. in a WSL2 install.
The issue is that Windows delivers libcuda.so, libcuda.so.1, and libcuda.so.1.1 as fully separate copies of the same file. 
The fix is just to remove libcuda.so and libcuda.so.1, and just make sym links for each of them to libcuda.so.1.1 
Run a shell as Administrator,  type "cmd" to get a non-powershell command line.
Then:
C:
cd \Windows\System32\lxss\lib
del libcuda.so
del libcuda.so.1 
mklink libcuda.so libcuda.so.1.1
mklink libcuda.so.1 libcuda.so.1.1 

when you're done, it will look like this:

As per @Phyx-Meow:

"Actually this is not relate to Arch, nor ArchWSL. It's caused by libcuda.so in your C:\Windows\System32\lxss\lib\ folder not a symbolic link, which is installed by nvidia driver. One solution to [remove] the warning is delete libcuda.so and libcuda.so.1 and use make symbolic link to libcuda.so.1.1. Command line: mklink <target file> <source file>. Note the command not work in powershell, you shall use cmd.exe."

:)

**Comment by ArrowRaider** [comment]
@John-Joubert 
This did not help me.  It still says `/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link` whenever ldconfig is run.

My directory listing in the one folder is this:
```
 Directory of C:\Windows\System32\lxss\lib

06/20/2022  08:48 PM    <DIR>          .
06/20/2022  08:48 PM    <SYMLINK>      libcuda.so [libcuda.so.1.1]
06/20/2022  08:48 PM    <SYMLINK>      libcuda.so.1 [libcuda.so.1.1]
12/15/2021  08:16 AM           141,464 libcuda.so.1.1
06/05/2021  08:06 AM           785,608 libd3d12.so
11/23/2021  01:55 AM         5,398,848 libd3d12core.so
06/05/2021  08:06 AM           827,904 libdxcore.so
12/15/2021  08:16 AM         5,962,912 libnvcuvid.so
12/15/2021  08:16 AM         5,962,912 libnvcuvid.so.1
12/15/2021  08:16 AM           424,400 libnvidia-encode.so
12/15/2021  08:16 AM           424,400 libnvidia-encode.so.1
12/15/2021  08:16 AM           201,880 libnvidia-ml.so.1
12/15/2021  08:16 AM           354,768 libnvidia-opticalflow.so
12/15/2021  08:16 AM           354,768 libnvidia-opticalflow.so.1
12/15/2021  08:16 AM        53,491,712 libnvwgf2umx.so
12/15/2021  08:16 AM           682,488 nvidia-smi
```

**Comment by PhyX-Meow** [comment]
@ArrowRaider Try restart wsl2, or restart your pc.

**Comment by BrainSlugs83** [comment]
@John-Joubert that worked for me... I'm wondering why this bug is closed if we still have to do this manual workaround. -- Why can't this just be fixed in WSL?

**Comment by geek111** [comment]
> Please review response post by @PhyX-Meow re: [yuk7/ArchWSL#248](https://github.com/yuk7/ArchWSL/issues/248). As he points out, it really has nothing to do with your Linux install. It's a simple fix in Windows. The solution he posts is for Arch, but the fix is exactly same for Ubuntu, etc. in a WSL2 install. The issue is that Windows delivers libcuda.so, libcuda.so.1, and libcuda.so.1.1 as fully separate copies of the same file. The fix is just to remove libcuda.so and libcuda.so.1, and just make sym links for each of them to libcuda.so.1.1
> 
> _Run a command line shell a**s Administrator**, type "**cmd**" to get a non-powershell command line._
> 
> Then type the following commands to create the problematic symbolic links:
> 
> **C: cd \Windows\System32\lxss\lib del libcuda.so del libcuda.so.1 mklink libcuda.so libcuda.so.1.1 mklink libcuda.so.1 libcuda.so.1.1**
> 
> when you're done, it will look like this:
> 
> **C:\Windows\System32\lxss\lib> DIR ... ... Directory of C:\Windows\System32\lxss\lib 03/15/2022 04:00 PM **
> ** . 03/15/2022 03:59 PM libcuda.so [libcuda.so.1.1] 03/15/2022 04:00 PM libcuda.so.1 [libcuda.so.1.1]**
> 
> Then, just finish your command you were running, in my case, the solution was just run "**apt reinstall libc-bin**". This is because libc-bin was getting the errors when I had run "apt upgrade -y" command. (see below)
> 
> The error I received in my "apt upgrade -y" command was two lines: #> **apt upgrade -y** .... < stuff deleted > ... **Processing triggers for libc-bin (2.31-0ubuntu9.7) ... /sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link** ... < stuff deleted > ...
> 
> As per @PhyX-Meow
> 
> _"Actually this is not relate to Arch, nor ArchWSL. It's caused by libcuda.so in your C:\Windows\System32\lxss\lib\ folder not a symbolic link, which is installed by nvidia driver. One solution to [remove] the warning is delete libcuda.so and libcuda.so.1 and use make symbolic link to libcuda.so.1.1. Command line: mklink . Note the command not work in powershell, you shall use cmd.exe."_
> 
> :)

When I do this things then have something like this:

> RuntimeWarning: Running on CPU now! Make sure your PyTorch version matches your CUDA.The unoptimized RealESRGAN is slow on CPU. If you want to disable it, please remove `--bg_upsampler` and `--face_upsample` in command.
>   warnings.warn('Running on CPU now! Make sure your PyTorch version matches your CUDA.'
> 

And CPU not GPU doing all :(

**Comment by valzargaming** [comment]
> cd \Windows\System32\lxss\lib del libcuda.so del libcuda.so.1 mklink libcuda.so libcuda.so.1.1 mklink libcuda.so.1 libcuda.so.1.1

I made a slight tweak to your command for anyone struggle getting this to work. Adding && between the various commands ensures proper evaluation from left to right, otherwise users might run into `The system cannot find the path specified`.

`cd C:\Windows\System32\lxss\lib && del libcuda.so && del libcuda.so.1 && mklink libcuda.so libcuda.so.1.1 && mklink libcuda.so.1 libcuda.so.1.1`

**Comment by bhaskoro-muthohar** [comment]
Why this issue is closed? I'm still experiencing this issue and I still have to do the manual workaround

**Comment by HEXDude** [comment]
> Why was this issue closed? The problem still persists for me, and I find myself having to use the manual 解决方法. Could someone take another look, please?

I have ran into this problem. @John-Joubert His comments works for me after a WSL  restart. You may considering a restart.

**Comment by PhyX-Meow** [comment]
> Why was this issue closed? The problem still persists for me, and I find myself having to use the manual workaround. Could someone take another look, please?

As formerly said, the issue has nothing to do with wsl itself. Linux programs require the file to be a symlink, while nvidia driver installed the file as a regular one. You should go for nvidia driver forum or linux community. We can do nothing here 😞

**Comment by parsley72** [comment]
> > Why was this issue closed? The problem still persists for me, and I find myself having to use the manual workaround. Could someone take another look, please?
> 
> As formerly said, the issue has nothing to do with wsl itself. Linux programs require the file to be a symlink, while nvidia driver installed the file as a regular one. You should go for nvidia driver forum or linux community. We can do nothing here 😞

Go to https://forums.developer.nvidia.com/t/wsl2-libcuda-so-and-libcuda-so-1-should-be-symlink/236301 and like/comment, maybe we'll get some traction.

**Comment by Harry84** [comment]
same issue..

**Comment by s3rgeym** [comment]
```ps
PS C:\Users\sergey> wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1702
```

**Comment by gomo** [comment]
I have created a Tensorflow container in docker installed in WSL, but with [this solution](https://github.com/microsoft/WSL/issues/5663#issuecomment-1068499676), Tensorflow can't find the GPU.

By running some process that produces this error and then putting it back into the file again, Tensorflow can find the GPU.

````
cd C:\Windows\System32\lxss\lib
ren libcuda.so libcuda.so.bak
ren libcuda.so.1 libcuda.so.1.bak
mklink libcuda.so libcuda.so.1.1
mklink libcuda.so.1 libcuda.so.1.1
```

Do something that produces this error.

```
cd C:\Windows\System32\lxss\lib
del libcuda.so
del libcuda.so.1
ren libcuda.so.bak libcuda.so
ren libcuda.so.1.bak libcuda.so.1
````

**Comment by jyono** [comment]
same issue....

**Comment by Rivgad** [comment]
Same issue. The manual binding workaround doesn't seem to help for me/

**Comment by jibnew** [comment]
Same with me. Workaround only survives until next nvidia driver update, then it must be done again.

**Comment by BrainSlugs83** [comment]
> Why was this issue closed? The problem still persists for me, and I find myself having to use the manual workaround. Could someone take another look, please?

Looks like this bug was closed as a duplicate of #5548 -- I totally missed that and thought this was closed because a workaround existed (which would be super lame) -- but it looks like #5548 is still open, so for further discussion we should go there I guess. 🙂

**Comment by 78Alpha** [comment]
This happens to be the first one to show online

**Comment by JohnRDOrazio** [comment]
> sudo apt reinstall libc-bin

this seems to take care of the issue for me

**Comment by jyono** [comment]
show stopping bug for me. done with windows and WSL 👋

**Comment by mcarman** [comment]
```
cd /usr/lib/wsl/lib
sudo rm libcuda.so libcuda.so.1
sudo ln -s libcuda.so.1.1 libcuda.so.1
sudo ln -s libcuda.so.1 libcuda.so
sudo ldconfig
```
Got this from the nvidia site. I screwed up the link. 
If you are on wsl, this may help.
It worked for me

**Comment by John-Joubert** [comment]
Thanks for the kind update!

I simply went there, removed the libcuda.so file, and make a symbolic link to the libcuda.so.1.1 file and named it libcuda.so.
And then everything went fine. No extra steps (at least thus far).

Thanks for the your kind suggestion, so nice of you!

________________________________

**Comment by donaldafeith** [comment]
What worked to fix it for me was

`sudo apt update`
`sudo apt install -y wget gnupg`
`wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin`
`sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600`
`sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub`
`sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"`
`sudo apt update`
`sudo apt install -y cuda`
`sudo ldconfig`

Didn't have to mess with any links on my computer or delete anything, move anything, or downgrade from WSL Ubuntu 22.04.

Hope this helps someone.
