### ISSUE TITLE
 CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by lpj0711** [microsoft/WSL#6098]
>>> import torch
>>> torch.cuda.is_available()
True
>>> a = torch.tensor(1)
>>> a.cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

windows：20231.1005

**Comment by noofaq** [comment]
the issue is fixed in the very latest Windows release 20236

**Comment by hanxiaotian** [comment]
I'm using 20241, but cuda is still not working in mu wsl. Previously, when I use 20176, it worked

**Comment by onomatopellan** [comment]
@hanxiaotian It still happens in some scenarios. The issue appears in the [build 20241 release notes](https://blogs.windows.com/windows-insider/2020/10/21/announcing-windows-10-insider-preview-build-20241/) so you will need to wait for a fix.
>We’re investigating GPU Compute scenarios, such as using CUDA and DirectML, not working inside of the Windows Subsystem for Linux (WSL).
