### ISSUE TITLE
got the error: out of memory ,when invoke cuda in wsl2.

### ISSUE THREAD

**Issue by before31** [microsoft/WSL#8447]
### Version

Microsoft Windows [版本 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

nvidia driver (on Windows), version: 512.77
cuda (installed in wsl2, only the cuda tookit, not reinstall nvidia driver in wsl2 ),version:10.2 or 11.6, both are tried, the same error.

### Repro Steps

1. setup Windows10 21H2
2. enabled wsl2
3. install the latest nvidia driver, version: 512.77 (I have 4*1080ti GPUs in this machine)
4. install cuda tookit in wsl2, by the instruction: [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=runfile_local)
5. In wsl2(Ubuntu20.04), run a java application that invoke cuda through jna. This application is a sample app to simplify the problem reproduction process. It looks like this:
>    public static void main(String[] args) {
            System.setProperty("jna.debug_load", "true");
        int[] deviceCount = new int[1];
        int result = WxCudaLibrary.INSTANCE.cudaGetDeviceCount(deviceCount);
        if (result == 0) {
            System.out.println("gpu check success:" + deviceCount[0]);
        } else {
            String msg = WxCudaLibrary.INSTANCE.cudaGetErrorString(result);
            System.out.println("gpu check failed:" + result + ",msg:" + msg);
        }
    }
6. got the error: gpu check failed:2,msg:out of memory
The same application runs well on Windows (Changed the library name).

### Expected Behavior

I can invoke cuda in wsl2 normally.

### Actual Behavior

- Any cuda apps got the same error: out of memory.
- In wsl2, the nvidia-smi program got:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 512.77       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0 Off |                  N/A |
| 23%   33C    P8    10W / 250W |    541MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:03:00.0 Off |                  N/A |
| 23%   29C    P8    11W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:82:00.0 Off |                  N/A |
| 23%   28C    P8    10W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:83:00.0 Off |                  N/A |
| 23%   27C    P8    10W / 250W |     11MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by before31** [comment]
Is any one here?

**Comment by before31** [comment]
Here is the logs. Thanks.

[WslLogs-2022-06-01_10-08-04.zip](https://github.com/microsoft/WSL/files/8810512/WslLogs-2022-06-01_10-08-04.zip)

**Comment by before31** [comment]
In addition, I need to add that my WDDM version is 1.3. I don't know if it has any impact. In my mind, the WDDM version should be changed to 3.x after I install the latest NVIDIA driver.

![image](https://user-images.githubusercontent.com/30918844/171551301-d5e42a9c-93a9-45ee-8c8c-a65f989c5d52.png)

**Comment by before31** [comment]
Is there anything new?

**Comment by OneBlue** [comment]
Thanks for the logs @before31. Once you get this out of memory error, can you also share the output of `dmesg` inside WSL ?

**Comment by before31** [comment]
1. I run my cudaapp and got the out of memory error.
2. I executed the `dmesg >dmesg.log` command inside the WSL. Here is the output:
[dmesg.log](https://github.com/microsoft/WSL/files/8858605/dmesg.log)

Thanks. @OneBlue

**Comment by before31** [comment]
Any updated?

**Comment by xiaojinyu-hhu** [comment]
How do you fix this problem?

**Comment by before31** [comment]
> How do you fix this problem?

The problem remains unresolved.

**Comment by Abdullah-Aldosari** [comment]
What is the PC/workstation that you are using?

**Comment by xiaojinyu-hhu** [comment]
> 

CPU
	Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz
        Supermicro X12DPG-OA6
        Directx 12
        No TPM2.0 (so this PC cannot update to win11)
System
       Window 10 22H2 19045.1865


The hardware may not support it.

**Comment by Abdullah-Aldosari** [comment]
I am using a Dell precision tower with windows 11 and with 4 quadro rtx 4000 and I am running into the same issue.

**Comment by CanisLupus518** [comment]
I am experiencing the same issue with windows 11, i7-12700KF, RTX 3070-Ti. Graphs for used memory only reach about half available GPU RAM, before the 
RuntimeError: CUDA error: out of memory

**Comment by thoj** [comment]
This has something to do with pin_memory on my system with Pytorch. Once i set pin_memory=False i can use all the memory on the GPU. Unfortunately this also reduces the performance quite a bit.

Probably something to do with this:
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-apps

Hope a fix is possible.

**Comment by maloletnik** [comment]
Having the same issue, docker under WSL.
Also when setting `pin_memory=False` the CUDA memory error goes away, but the training process is much slower.

**Comment by QCHighing** [comment]
Having the same issue, docker under WSL.
Need to set pin_memory=False  for the dataloader of pytorch.

**Comment by ltorres6** [comment]
I have the same pinned memory issue with Ubuntu 18.04 and Cupy. It seems that I can only set a small amount of memory as pinned memory (much smaller than RAM and VRAM). Ulimit states 64 kilobytes is my maximum locked memory, but I can't seem to change this setting to test if this is my problem. Does anyone else have a workaround?

**Comment by satoshi-ikehata** [comment]
Same problem here. I got an error of "out of gpu memory" when using pin_memory=True of PyTorch on WSL2 (Windows11). 
pin_memory=False resolved the error but sacrificed the performance gain

**Comment by al1enjesus** [comment]
Hi all! 
Had the same problem! Also OOM, although there should be enough video memory.
From the script from here, replacing cpu with cuda:0 you can see that WSL won't allow available video memory to be allocated.  
https://github.com/huggingface/diffusers/issues/807#issuecomment-1276584125

Took me three weekends to solve it. Tried different versions of fixes: built Cuda from scratch, tried different Ubuntu versions, different Windows versions.

In the end I swapped Windows 10 -> Windows 11 Pro
11.0.22621 Build 22621
But, even with windows 11 with wsl installed and Ubuntu 22.04 distribution there was this bug.
Installing exactly Ubuntu 20.04 + Windows 11 helped. The driver is installed in windows, on ubuntu I use miniconda, without any manual cuda setups.
Ubuntu from here: https://www.microsoft.com/store/productId/9MTTCL66CPXJ.
Be sure to update wsl and ubuntu, and also reboot the entire system at the end.

Yeah, it's not normal to have to do rain dances to work properly under WSL, so it needs a fix. But if you need it urgently, I said what worked for me.

**Comment by MrWong99** [comment]
Got the same issue today with https://github.com/ggerganov/whisper.cpp

WSL 2
Nvidia RTX 4090
Arch Linux
cuda 12.5.0-1

**Comment by LordMilutin** [comment]
I have the same issue. There is no fix for this?

**Comment by deKeijzer** [comment]
This is still present, as observed in https://github.com/ultralytics/ultralytics/issues/14367 . The CUDA out of memory error, when there is plenty of memory left, is not present when not using WSL2.

**Comment by erklem** [comment]
I am experiencing the same issue. I can run faster-whisper just fine in native Windows, but _running the same code_ in WSL2 (on the same machine) causes CUDA out of memory.

**Hardware**
Quadro T2000 GPU (4 GB vRAM)
Intel i7-10850H CPU
32 GB RAM

**Windows System**
Windows 10 22H2
CUDA 12.6
cuDNN 8.9.27

**WSL System**
WSL Version: 2.2.4.0
Kernel Version: 5.15.153.1-2
Pytorch 2.4.0 with CUDA 12.4

**Faster-Whisper Details**
faster-whisper: 1.0.1
model_name: large-v3
compute_type: float-16 (also tried int8)
batch_size: 16

**Comment by zhzLuke96** [comment]
any update here? in 2025

**Comment by LIEGU0317** [comment]
Any update on this? 2025.06.06

**Comment by fffonion** [comment]
If this helps, I figured out this was caused by incompatible driver with the cuda runtime.

Which version of CUDA shouldn't matter, as long as it's supported by the driver and what your card supports.

```
# remove those from ubuntu
sudo apt-get purge -y '*nvidia-driver*' '*nvidia-kernel*' '*libnvidia*'
# install from nvidia
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-9
# most time just install the following is enough
# sudo apt install cuda-compiler-12-9 cuda-crt-12-9 cuda-cudart-12-9 cuda-cudart-dev-12-9 cuda-nvcc-12-9 libcublas-12-9 libcublas-dev-12-9 libcufft-12-9 libcufft-dev-12-9  libcurand-dev-12-9

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/wsl/lib:/usr/local/cuda-12.9/lib64
export PATH=$PATH:/usr/local/cuda-12.9/bin

# recompile your application
```
