### ISSUE TITLE
Failed to properly shut down NVML: GPU access blocked by the operating system

### ISSUE THREAD

**Issue by Marietto2008** [microsoft/WSL#9166]
### Version

22.000

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.8 and 6.0 

### Distro Version

Ubuntu 22.10

### Repro Steps

Hello to everyone.

Premising that I’m using “Microsoft Windows 11 [Version 10.0.22000.1219]”,I have installed Ubuntu 22.04 on top of it and then I’ve upgraded Ubuntu 22.04 to 22.10 and I’ve upgraded the driver for my RTX 2080 ti on the host os. After this,I have installed CUDA inside the WSL2 / Ubuntu following this mini tutorial :

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_network

These are the commands that I have issued :

```
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda

```
at this point I did :

`apt install nvidia-utils-510`

because without installing this package,it won’t find the utility nvidia-smi. But this is the error that I’ve got next :

```
# nvidia-smi

Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system

```
what should I do now ? The driver installed on the host os is version : 31.0.15.2686

### Expected Behavior

that nvidia-smi outputs the informations related to my gpu and that I can use it inside the WSL2 environment.

### Actual Behavior

this is what happens when I launch nvidia-smi inside ubuntu 22.10 :

```
nvidia-smi

Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system
```

**Comment by koltenfluckiger** [comment]
I had my time messing around with the drivers. I was able to get it working on 515. 
![Screenshot_20221117_103906](https://user-images.githubusercontent.com/41795395/202629148-995962cb-6230-4e25-8bb1-4794ebd93ac5.png)

![Screenshot_20221117_104123](https://user-images.githubusercontent.com/41795395/202629223-ed5b2c69-e775-4d9f-87fd-4a8bc5b794ed.png)

Heres my installed lib packages. 

Here's the repos as well.

archive_uri-https_developer_download_nvidia_com_compute_cuda_repos_wsl-ubuntu_x86_64_-jammy.list
cuda-wsl-ubuntu-11-8-local.list
cudnn-local-ubuntu2204-8.6.0.163.list
nccl-local-ubuntu2204-2.15.5-cuda11.8.list
nv-tensorrt-local-ubuntu2204-8.5.1-cuda-11.8.list

Good luck. If I remember right I had to install the drivers and the kernel libs first.

**Comment by Marietto2008** [comment]
your instructions sounds vague for me. Tell me where to get the repos that you used.

**Comment by koltenfluckiger** [comment]
Repos can be found by googling the text. It's a mix of the wsl and 22.04 repos.

**Comment by Marietto2008** [comment]
I tried to google the text,but I found nothing.
