### ISSUE TITLE
Failed to initialize NVML: GPU access blocked by the operating system

### ISSUE THREAD

**Issue by loliq** [microsoft/WSL#9938]
### Windows Version

Windows 10 [19045.2728]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04 

### Repro Steps

I install wsl2 in Windows 10 [19045.2728]
![image](https://user-images.githubusercontent.com/26076957/230893262-c1a1b2b3-af83-435c-9c5c-ebdff5f5244b.png)

In Windows, “nvidia-smi” output is :
![image](https://user-images.githubusercontent.com/26076957/230893115-17ec64e0-518e-434d-8031-f1c38316b309.png)

but in wsl2, output is : 
![image](https://user-images.githubusercontent.com/26076957/230893364-de633ef4-beb0-4854-8f13-83c8d58c484d.png)

Below are the solutions I have tried that didn't work：
1. log in with administrator privileges
2. update the driver to the latest version
3. install cuda toolkits 

My file list in `C:\Windows\System32\lxss\lib` is : 

![image](https://user-images.githubusercontent.com/26076957/230894204-d85b9187-fb81-44c3-9328-b570357877f6.png)

### Expected Behavior

that nvidia-smi outputs the informations related to my gpu and that I can use it inside the WSL2 environment.

### Actual Behavior

this is what happens when I launch nvidia-smi inside ubuntu 22.04 :
```
nvidia-smi

Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system
```

**Comment by fschvart** [comment]
I have the exact same problem

**Comment by fschvart** [comment]
Hi, 
In my case the issue was that WSL doesn't support A100 GPUs

**Comment by loliq** [comment]
> Hi, In my case the issue was that WSL doesn't support A100 GPUs

Thank you very much, I guess it was the problem， I have tried other machine which use 3090 and it works.

**Comment by loliq** [comment]
> Hi, In my case the issue was that WSL doesn't support A100 GPUs

Thank you very much, I guess it was the problem， I have tried other machine which use 3060 and it works.

**Comment by loliq** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

Thank you for replying, the attachment is log file. 
[WslLogs-2023-04-12_11-08-54.zip](https://github.com/microsoft/WSL/files/11206789/WslLogs-2023-04-12_11-08-54.zip)

**Comment by lpdink** [comment]
I have encountered a similar problem. nvidia-smi works well in wsl2, but it doesn't work properly in the docker container started in wsl2, with error "Failed to initialize NVML: GPU access blocked by the operating system".
![aebf03e8daa69b32bdc7e609ecc194d8 (1)](https://user-images.githubusercontent.com/51897400/231663819-0d4645d2-7a77-4f45-a960-2cae3c86ea9d.jpg)
I use the official image provided by Pytorch and am confident that Docker-ce and nvidia_container_toolkit has been installed correctly. In fact, when I use the same installation script in the Ubuntu system, the GPU in the container works well.
Here is my system version info:
![QQ截图20230413134621](https://user-images.githubusercontent.com/51897400/231665198-965bed5e-0ca0-4eac-97f6-8011fff474dc.png)
![QQ截图20230413134729](https://user-images.githubusercontent.com/51897400/231665234-3f707121-e8cc-465a-87e2-f7e66cab9556.png)
Looking forward to your reply, thank you in advance for your help

**Comment by bsekachev** [comment]
Exactly the same problem like @loliq has.
Yesteday worked fine, today does not work anymore.

Windows has updated last night.
Installed: KB5025239, KB2267602, KB890830

**Comment by alf-wangzhi** [comment]
> I have encountered a similar problem. nvidia-smi works well in wsl2, but it doesn't work properly in the docker container started in wsl2, with error "Failed to initialize NVML: GPU access blocked by the operating system". ![aebf03e8daa69b32bdc7e609ecc194d8 (1)](https://user-images.githubusercontent.com/51897400/231663819-0d4645d2-7a77-4f45-a960-2cae3c86ea9d.jpg) I use the official image provided by Pytorch and am confident that Docker-ce and nvidia_container_toolkit has been installed correctly. In fact, when I use the same installation script in the Ubuntu system, the GPU in the container works well. Here is my system version info: ![QQ截图20230413134621](https://user-images.githubusercontent.com/51897400/231665198-965bed5e-0ca0-4eac-97f6-8011fff474dc.png) ![QQ截图20230413134729](https://user-images.githubusercontent.com/51897400/231665234-3f707121-e8cc-465a-87e2-f7e66cab9556.png) Looking forward to your reply, thank you in advance for your help

I encountered the same problem. Has it been resolved? Does this error mean that GPU cannot be used?

**Comment by lpdink** [comment]
Yeah，just see: https://github.com/microsoft/WSL/issues/9962 @alf-wangzhi

**Comment by alf-wangzhi** [comment]
thank you so much. it is means a lot @lpdink

**Comment by anton-petrov** [comment]
The problem was solved, time to close this issue.

**Comment by mikeggh** [comment]
Was it actually solved?  All I am seeing is that people are downgrading to solve...

**Comment by qwqawawow** [comment]
I got this error on my machine 
```
WSL version： 2.2.4.0
version： 5.15.153.1-2
WSLg version： 1.0.61
MSRDC version： 1.2.5326
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.26091.1-240325-1447.ge-release
Windows version： 10.0.22631.3737
```
and the kernel is `6.6.32-microsoft-standard-WSL2`
compiled by myself? 
Any suggestions?

**Comment by bert-jan** [comment]
I have the same issue with Nvidia A16.

`WSL version： 2.1.5.0
version： 5.15.146.1-2
WSLg version： 1.0.60
MSRDC version： 1.2.5105
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version： 10.0.19045.3570`

**Comment by Zhiwei-Zhai** [comment]
I have the same issue, with:

system: windows 10, 22H2, 19045.4651,    GPU: Nvidia Tesla v100
Ubuntu-22.04 
```
WSL version： 2.3.13.0
内核version： 6.6.36.3-1
WSLg version： 1.0.63
MSRDC version： 1.2.5326
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.26100.1-240331-1435.ge-release
Windows version： 10.0.19045.4651
```

**Comment by Rahman2001** [comment]
Here, I found solution in #9962 that says:

> Inside the file /etc/nvidia-container-runtime/config.toml change no-cgroups from true to false

It worked for me. Hope it does for you too.

**Comment by ankrwu** [comment]
Inside the file /etc/nvidia-container-runtime/config.toml change no-cgroups from true to false

**Comment by umarbutler** [comment]
Very bizzare, this happened to me randomly but it was fixed after restarting...

**Comment by AsunwithAfterglow** [comment]
i have the same question like  you.
you can use VGPU GRID driver to  set your NV card mode from TCC to WDDM.
and all problem solve.

**Comment by lijiajga** [comment]
This is a problem with my system.

<img width="208" alt="Image" src="https://github.com/user-attachments/assets/0eb1ec3d-8b6f-47ed-bcf8-6be495b66cc8" />

<img width="218" alt="Image" src="https://github.com/user-attachments/assets/f2d1d999-cf96-4c4c-89c6-218c8f6d7f31" />

<img width="322" alt="Image" src="https://github.com/user-attachments/assets/12ca19bb-b82c-4994-90e5-e2f3ea01ca21" />

This is my log file：
[WslLogs-2025-04-27_17-00-05.zip](https://github.com/user-attachments/files/19932924/WslLogs-2025-04-27_17-00-05.zip)

**Comment by lijiajga** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

This is a problem with my system.

![Image](https://github.com/user-attachments/assets/20125c61-d87f-4834-ad09-eb676475cc8c)

![Image](https://github.com/user-attachments/assets/1bf67268-2d41-4c27-8610-89d6b0e50570)

![Image](https://github.com/user-attachments/assets/344f1e4a-6a13-4ec2-98d7-2e6e8ce616d4)
This is my log file：
[WslLogs-2025-04-27_17-00-05.zip](https://github.com/user-attachments/files/19933028/WslLogs-2025-04-27_17-00-05.zip)
